### ISSUE TITLE
Registration or publication?

### ISSUE THREAD

**Issue by chartgerink** [p2pcommons/specs#19]
On the [Liberate Science Slack](https://join.slack.com/t/libscie/shared_invite/enQtNzUxMDIwODg3OTg5LTRiMThlZTlmYjBmYWQzOWU5YzM5NDQzNjAyMmZjMTkzN2VkMDUyOGVhNzViZmM1MGZkMDViMzNkNDY2OTYyNzA), we had a discussion about whether we should replace the concept of `registration` with `publication`. We didn't really have a clear answer, and would like to open it up for discussion. The main question is:

> Would you **register** content to your profile, or **publish** content to your profile?

Content modules can contain text, data, video's, code, and virtually any type of information. 

Publication traditionally refers to text, but in the digital age has definitely become more encompassing. It also implies 'making public' for others to consume.

Registration usually means to associate already public content with your identity (e.g., you don’t publish a house, because it already exists in the public; HT @juliangruber). This refers more to indexing (HT @nehamoopen).

This is open to discussion and doesn't necessarily only revolve around the most correct naming, but also the most intuitive one?

**Comment by chartgerink** [comment]
My thinking is slowly shifting to prefer `publication` due to the clarity it gives that it is 'the action of making something generally known.' It also allows users to bring a lot of their familiar language with, even if we're changing the act of what and how you publish (coming from scholarly research anyway).

We're already doing our best in the p2pcommons space to make sure people have legal certainty to reuse materials by mandating the CC0 Public Domain Dedication, and I am starting to think any lack of clarity in `registration` might hamper this.

I was reading [Copyright and the distributed peer-to-peer web](https://www.ctrl.blog/entry/copyright-p2p-dweb) just now, which gave me some more conviction on my new preference.

**Comment by juliangruber** [comment]
Good thinking, maybe `publication` isn't scary enough still. Something will be made public and public forever, right? At the moment I can't think of a term that implies that more precisely than "to publish".

**Comment by mzelst** [comment]
I saw the issue is still open, so wanted to add some on top of the existing conversation. I'd favor publication over registration for its intuitive connection to the verb of 'to publish' as @juliangruber mentioned. More short-term thinking: most people currently using the word publishing to describe how they publish will easier associate this; registration requires more explanation for all current users and might scare them off.

Definition wise, registration means 'an entry into a register' (like the house example), which is not really what p2pcommons is about if I understand it correctly.

**Comment by chartgerink** [comment]
Closing this issue and moving forward with the publication terminology :)
