### ISSUE TITLE
module spec questions

### ISSUE THREAD

**Issue by dpaez** [p2pcommons/specs#3]
With the progress on the sdk v0.2.0+ some questions arise regarding some [fields](https://github.com/p2pcommons/specs/blob/master/module.md#namevalues) and desired usage:
- `type` is said to be `content` or `profile` and it is used to distinguish a module. But it is also mentioned that it contain more information, like a namespace and it only matters if it ends with `content` or `profile`. This can be confusing and hard to maintain. I propose to keep the type field with only some possible values (`content`, `profile`) and add a appType which can contain the app-level type, eg: `myapp-content` | `myapp-profile`. The type field continues to be required and the appType is optional.
- if we want to list [all writable modules of some type](https://docs.google.com/spreadsheets/d/1Hp4gIUVNePO33lGcYeK8dOwY6EZWCQrL7XrURIILslg/edit#gid=0&range=A7) should we also keep archive metadata on the local db? This can have more sense when the register behavior is implemented, and the metadata of a new module is added which can (highly) possibly be an outside/external/non-writable dat. This is also connected with the effect of the `init` method which creates a new module (dat) and thus this new module is writable. Here the proposal is to add dat.metadata to the local db. What do you think?

**Comment by chartgerink** [comment]
`modType` maybe? I put it like that because down the line it would be the goal to use wikidata identifiers to help us identify what or who the modules are (e.g., `Q41719-content` for hypothesis content). I agree it might be hard to maintain, when people technically could start chaining anything before `*-content`.

The local db should contain all the metadata, whether it's writable, and maybe some data from the hyperdrive about the last modified time (although that cannot be 100% trusted). This is something the interoperability spec should write out further, so any ideas are very welcome. You said the local db is in leveldb --- does that work in other languages as well? (just making sure given my lack of experience with it)

**Comment by dpaez** [comment]
I'm going to add the `modType` field. 

Yup. There are many more leveldb implementations in different languages. 

For the particular dat archive metadata, should we use a `dat` field and put everything inside or something different?

**Comment by chartgerink** [comment]
Okay, great. I'll add a bit to the spec. If you have ideas about how to implement the modType, let me know :)

**Comment by dpaez** [comment]
Currently the modType is just a string. We check if it ends with `profile` or `content`. This way the `type` field is only limited to `profile` or `content`.

**Comment by chartgerink** [comment]
`modType` is `subtype` to prevent confusion, and should be an empty string by default (i.e., `subtype: ''`).

The `writable` info is important for the local db, but should not be in the module itself. Maybe this diagram helps a tiny bit?

![p2pcommons-db-cache](https://user-images.githubusercontent.com/2946344/67013053-c5a22300-f0f2-11e9-8e6b-7d1e80731d5a.png)
